---
title: "Fit DIABIMMUNE"
author: "Siyuan Ma"
output: html_document
---

```{r set up}
rm(list = ls())
library(magrittr)
library(ggplot2)

dir_output <- "results/DIABIMMUNE"
dir.create(dir_output, showWarnings = TRUE, recursive = TRUE)
```

```{r fit}
load("data/DIABIMMUNE/X_array.RData")

l_fit_microTensor <- list()
for(i in seq(1, 5)) {
  set.seed(i)
  l_fit_microTensor[[i]] <- microTensor::microTensor(
    X = X_array, R = 3, 
    nn_t = TRUE, ortho_m = TRUE,
    weighted = TRUE,
    control = list(L_init = 2,
                   gamma = 2,
                   maxit = 1000,
                   verbose = TRUE,
                   debug_dir = paste0(dir_output, "/fit/", i)))
}
fit_microTensor <- l_fit_microTensor %>% 
  purrr::map_dbl(~ min(.x$fitting$obj)) %>% 
  {order(.)[1]} %>% 
  {l_fit_microTensor[[.]]}
save(fit_microTensor, file = paste0(dir_output, "/fit_microTensor.RData"))

l_fit_ctf <- list()
for(i in seq(1, 5)) {
  l_fit_ctf[[i]] <- 
    microTensor::ctf(
    X = X_array, R = 3)
}
fit_ctf <- l_fit_ctf %>% 
  purrr::map_dbl(~ min(.x$fitting$obj)) %>% 
  {order(.)[1]} %>% 
  {l_fit_ctf[[.]]}
save(fit_ctf, file = paste0(dir_output, "/fit_ctf.RData"))

fit_pca <- microTensor::pca(X_array, R = 3)
save(fit_pca, file = paste0(dir_output, "/fit_pca.RData"))
```

```{r check R}
set.seed(5)
R <- 10
fit_long <- microTensor::microTensor(
  X = X_array, R = R, 
  ortho_m = TRUE,
  nn_t = FALSE,
  weighted = TRUE,
  control = list(
    L_init = 3,
    gamma = 2,
    abs_tol = 1e-4,
    rel_tol = 1e-4,
    maxit = 5000,
    verbose = FALSE))
negLogLiks <- seq(1, R) %>% 
  purrr::map_dbl(function(i_R){
    Yhat <- microTensor::get_Yhat(
      result = list(
        lambda = fit_long$lambda[seq(1, i_R)],
        m = fit_long$m[, seq(1, i_R), drop = FALSE],
        s = fit_long$s[, seq(1, i_R), drop = FALSE],
        t = fit_long$t[, seq(1, i_R), drop = FALSE]
      )
    )
    microTensor::negLogLik_cpp(
      X = X_array,
      Yhat = Yhat,
      wt = matrix(1, nrow = dim(X_array)[2], ncol = dim(X_array)[3]),
      lambda = 0,
      vm = rep(0, dim(X_array)[1]),
      vs = rep(0, dim(X_array)[2]),
      vt = rep(0, dim(X_array)[3])
    )
  })

# zero
negLogLiks <- 
  c(microTensor::negLogLik_cpp(
      X = X_array,
      Yhat = array(0, dim(X_array)),
      wt = matrix(1, nrow = dim(X_array)[2], ncol = dim(X_array)[3]),
      lambda = 0,
      vm = rep(0, dim(X_array)[1]),
      vs = rep(0, dim(X_array)[2]),
      vt = rep(0, dim(X_array)[3])
    ),
    negLogLiks)

tb_plot <- tibble::tibble(
  R = seq(0, R),
  negLogLiks = negLogLiks
) 
  

p <- tb_plot %>% 
  ggplot(aes(x = R,
             y = negLogLiks)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  ylab("Negative log-likelihood") +
  ggtitle("DIABIMMUNE R")
save(fit_long, file = "results/DIABIMMUNE/fit_long.RData")
ggsave(p, filename = "results/DIABIMMUNE/select_R.pdf",
       width = 5, height = 5)

```



```{r check goodness-of-fit}
load(paste0(dir_output, "/fit_microTensor.RData"))
load(paste0(dir_output, "/fit_ctf.RData"))
load(paste0(dir_output, "/fit_pca.RData"))
load("data/DIABIMMUNE/X_array.RData")

Yhat_microTensor <- microTensor::get_Yhat(fit_microTensor)
expY <- exp(Yhat_microTensor)
expYsum_m <- apply(expY, c(2, 3), sum)
phat_microTensor <- 
  vapply(seq_len(dim(X_array)[1]),
         function(i) expY[i, , ] / expYsum_m,
         matrix(0.0, nrow = dim(X_array)[2], ncol = dim(X_array)[3]))
phat_microTensor <- 
  aperm(phat_microTensor, perm = c(3, 1, 2))

Yhat_ctf <- microTensor::get_Yhat(fit_ctf)
expY <- exp(Yhat_ctf)
expYsum_m <- apply(expY, c(2, 3), sum)
phat_ctf <- 
  vapply(seq_len(dim(X_array)[1]),
         function(i) expY[i, , ] / expYsum_m,
         matrix(0.0, nrow = dim(X_array)[2], ncol = dim(X_array)[3]))
phat_ctf <- 
  aperm(phat_ctf, perm = c(3, 1, 2))

Yhat_pca_mat <-  fit_pca$m %*% (t(fit_pca$s_full) * fit_pca$lambda)
Yhat_pca <- array(NA, dim(X_array))
for(i in seq_len(nrow(Yhat_pca_mat))) {
  Yhat_pca[i, , ] <-  Yhat_pca_mat[i, ]
}
expY <- exp(Yhat_pca)
expYsum_m <- apply(expY, c(2, 3), sum)
phat_pca <- 
  vapply(seq_len(dim(X_array)[1]),
         function(i) expY[i, , ] / expYsum_m,
         matrix(0.0, nrow = dim(X_array)[2], ncol = dim(X_array)[3]))
phat_pca <- 
  aperm(phat_pca, perm = c(3, 1, 2))


phat_data <- array(NA, dim(X_array))
Xsum_m <- apply(X_array, c(2, 3), sum)
phat_data <- 
  vapply(seq_len(dim(X_array)[1]),
         function(i) X_array[i, , ] / Xsum_m,
         matrix(0.0, nrow = dim(X_array)[2], ncol = dim(X_array)[3]))
phat_data <- 
  aperm(phat_data, perm = c(3, 1, 2))

tb_diff <- 
  list(phat_microTensor,
       phat_ctf,
       phat_pca) %>% 
  purrr::map2_dfr(
    c("microTensor", "CTF", "PCA"),
    function(i_phat, i_method) {
      tibble::tibble(
        diff = abs(i_phat - phat_data) %>% 
          apply(c(2, 3), mean) %>% 
          as.vector(),
        method = i_method
      )
    }
  ) %>% 
  dplyr::filter(!is.na(diff)) %>% 
  dplyr::mutate(method = factor(method, levels = c("PCA", "CTF", "microTensor")))
p_diff <- tb_diff %>% 
  ggplot(aes(x = method, y = diff)) +
  geom_boxplot() +
  theme_bw() +
  theme(axis.title.x = element_blank()) +
  ylab("Absolute difference in observed and \n method-based microbial profiles")
```

```{r visualization}
load(paste0(dir_output, "/fit_microTensor.RData"))
load(paste0(dir_output, "/fit_ctf.RData"))
load(paste0(dir_output, "/fit_pca.RData"))
load("data/DIABIMMUNE/df_samples.RData")
df_subjects <- df_samples %>% 
  dplyr::group_by(subjectid) %>% 
  dplyr::slice(1) %>% 
  dplyr::ungroup()
load("data/DIABIMMUNE/X_array.RData")
feature_names <- dimnames(X_array)[[1]]
subject_names <- dimnames(X_array)[[2]]
time_names <- dimnames(X_array)[[3]]


mat_tax <- feature_names %>% 
  stringr::str_split_fixed(stringr::fixed("|"), n = 6)
percs <- fit_microTensor$lambda^2 / sum(fit_microTensor$lambda^2) * 100
ps <- c(1, 2) %>% 
  purrr::map(function(r) {
    # feature
    df_m <- microTensor::create_loading(fit_microTensor,
                           feature_names = feature_names,
                           subject_names = subject_names,
                           time_names = time_names,
                           class = "feature") %>% 
      dplyr::mutate(
        feature_plot = 
          microTensor::betterGeneraNames(mat_tax[, 3],
                            mat_tax[, 4],
                            mat_tax[, 5],
                            mat_tax[, 6])) %>% 
      dplyr::mutate(m = !!sym(paste0("Axis ", r)))
    
    df_plot <- 
      rbind(
      df_m %>%
        dplyr::arrange(-df_m[["m"]]) %>%
        dplyr::slice(seq_len(5)),
      df_m %>%
        dplyr::arrange(df_m[["m"]]) %>%
        dplyr::slice(seq_len(5)) %>%
        {.[seq(5, 1), ]}
    ) %>%
      dplyr::mutate(feature_plot = factor(feature_plot, 
                                          levels = rev(feature_plot)))
    
    p_feature <- df_plot %>% 
      ggplot(aes(y = m, x = feature_plot)) +
      geom_bar(stat = "identity") +
      coord_flip() +
      theme_bw() +
      theme(axis.title.y = element_blank()) +
      ylab("Feature loading") +
      ggtitle(" ")
    
    # subject
    tb_loading <- microTensor::create_loading(
      fit_decomp = fit_microTensor,
                                 feature_names = feature_names,
                                 subject_names = subject_names,
                                 time_names = time_names,
                                 class = "subject")
    tb_loading <- tb_loading %>% 
      dplyr::left_join(df_samples %>% 
                         dplyr::group_by(subjectid) %>% 
                         dplyr::slice(1) %>% 
                         dplyr::ungroup(), 
                       by = c("Subject" = "subjectid")) %>% 
      dplyr::mutate(Csection = ifelse(csection,
                                      "C-section",
                                      "Vaginal"),
                    Loading = !!sym(paste0("Axis ", r)))
    p_subject <- tb_loading %>% 
      ggplot(aes(x = Csection,
                 y = Loading)) +
      geom_boxplot(outlier.shape = NA) +
      geom_point(position = position_jitter(width = 0.25)) +
      theme_bw() +
      xlab("") +
      ylab("Subject loading") + 
      ggtitle("")
    
     return(list(p_feature,
                p_subject))
  })


p_main <- 
  cowplot::plot_grid(ps[[1]][[1]], ps[[1]][[2]],
                     nrow = 1,
                     rel_widths = c(1, 0.6),
                     labels = c(paste0("B) Axis ", 1,
                                       " (", round(percs[1], 2),
                                       "%)"),
                                "")) %>% 
  cowplot::plot_grid(p_diff, ., labels = c("A)", ""),
                     nrow = 1, rel_widths = c(0.5, 1))
ggsave(p_main, file = "figures/figure7/figure_DIABIMMUNE.pdf",
       width = 12, height = 4.5)
```

```{r check time trends}
# df_subjects <- df_samples %>% 
#   dplyr::group_by(subjectid) %>%
#   dplyr::slice(1) %>% 
#   dplyr::ungroup() %>% 
#   dplyr::arrange(factor(subjectid, levels = dimnames(X_array)[[2]])) %>% 
#   dplyr::select(subjectid, csection)
# 
# feature_bac <- dimnames(X_array)[[1]] %>% 
#   stringr::str_subset("Dehalobacterium")
# feature_fae <- dimnames(X_array)[[1]] %>% 
#   stringr::str_subset("Barnesiella") %>% 
#   {.[3]}
# feature_bif <- dimnames(X_array)[[1]] %>% 
#   stringr::str_subset("Desulfovibrio") %>% 
#   {.[2]}
# X_rel <- apply(X_array, c(2, 3), function(x) x / sum(x))
# c(feature_bac, feature_fae, feature_bif) %>% 
#   purrr::map2_dfr(
#     c("Bacteroides", "Faecalibacterium", "Bifidobacterium"),
#     function(feature_full, feature_name) {
#       data.frame(X_rel[feature_full, , ], check.names = FALSE) %>% 
#         tibble::rownames_to_column("subjectid") %>% 
#         tidyr::pivot_longer(cols = -subjectid,
#                             names_to = "month",
#                             values_to = "rel_abd") %>% 
#         dplyr::mutate(month = as.numeric(month)) %>% 
#         dplyr::filter(!is.na(rel_abd)) %>% 
#         dplyr::left_join(df_subjects, by = "subjectid") %>% 
#         dplyr::mutate(feature = feature_name)
#     }) %>% 
#   dplyr::arrange(month) %>% 
#   dplyr::mutate(month = forcats::as_factor(month)) %>% 
#   ggplot(aes(x = month, y = rel_abd, color = csection)) +
#   geom_boxplot() +
#   facet_wrap(~feature, nrow = 3)
# 
# tb_loading <- microTensor::create_loading(fit_decomp = fit_microTensor,
#                                           feature_names = feature_names,
#                                           subject_names = subject_names,
#                                           time_names = time_names,
#                                           class = "sample")
# 
# tb_loading <- tb_loading %>% 
#   dplyr::mutate(Time = as.integer(as.character(Time))) %>% 
#   dplyr::left_join(df_samples %>% 
#                      dplyr::group_by(subjectid) %>% 
#                      dplyr::slice(1) %>% 
#                      dplyr::ungroup(), 
#                    by = c("Subject" = "subjectid")) 
# 
# r <- 2
# tb_loading_avg <- tb_loading %>% 
#   dplyr::group_by(Time, csection) %>% 
#   dplyr::summarise(mean_loading = mean(!!sym(paste0("Axis ", r)), na.rm = TRUE),
#                    se_loading = sd(!!sym(paste0("Axis ", r)), na.rm = TRUE) / sqrt(dplyr::n())) %>% 
#   dplyr::ungroup()
#     
# p_time <- tb_loading_avg %>% 
#   dplyr::filter(!is.na(csection)) %>% 
#   ggplot(aes(x = Time, y = mean_loading,
#              color = csection)) +
#   geom_line(position = position_dodge(width = 0.5)) +
#   geom_point(position = position_dodge(width = 0.5)) +
#   geom_errorbar(aes(ymax = mean_loading + se_loading,
#                     ymin = mean_loading - se_loading),
#                 position = position_dodge(width = 0.5),
#                 width = 0.5) +
#   theme_bw() +
#   labs(colour="Diet group") +
#   xlab("Study day") +
#   ylab("Group average sample loading") +
#   ggtitle("")
```

```{r supplementals}
p_supps <- list(fit_pca,
                fit_ctf) %>% 
  purrr::map2(
    c("PCA", "CTF"),
    function(fit_decomp,
             method) {
      percs <- fit_decomp$lambda^2 / sum(fit_decomp$lambda^2) * 100
      ps <- c(1, 2) %>% 
        purrr::map(function(r) {
          # feature
          df_m <- microTensor::create_loading(
            fit_decomp,
                                 feature_names = feature_names,
                                 subject_names = subject_names,
                                 time_names = time_names,
                                 class = "feature") %>% 
            dplyr::mutate(
              feature_plot = 
                microTensor::betterGeneraNames(mat_tax[, 3],
                                  mat_tax[, 4],
                                  mat_tax[, 5],
                                  mat_tax[, 6])) %>% 
            dplyr::mutate(m = !!sym(paste0("Axis ", r)))
          
          df_plot <- rbind(
            df_m %>% 
              dplyr::arrange(-df_m[["m"]]) %>% 
              dplyr::slice(seq_len(5)),
            df_m %>% 
              dplyr::arrange(df_m[["m"]]) %>% 
              dplyr::slice(seq_len(5)) %>% 
              {.[seq(5, 1), ]}
          ) %>% 
            dplyr::mutate(feature_plot = factor(feature_plot, 
                                                levels = rev(feature_plot)))
          
          p_feature <- df_plot %>% 
            ggplot(aes(y = m, x = feature_plot)) +
            geom_bar(stat = "identity") +
            coord_flip() +
            theme_bw() +
            theme(axis.title.y = element_blank()) +
            ylab("Feature loading") +
            ggtitle(" ")
          
          # subject
          tb_loading <- microTensor::create_loading(
            fit_decomp = fit_decomp,
                                       feature_names = feature_names,
                                       subject_names = subject_names,
                                       time_names = time_names,
                                       class = "subject")
          tb_loading <- tb_loading %>% 
            dplyr::left_join(df_samples %>% 
                               dplyr::group_by(subjectid) %>% 
                               dplyr::slice(1) %>% 
                               dplyr::ungroup(), 
                             by = c("Subject" = "subjectid")) %>% 
            dplyr::mutate(Csection = ifelse(csection,
                                            "C-section",
                                            "Vaginal"),
                          Loading = !!sym(paste0("Axis ", r)))
          p_subject <- tb_loading %>% 
            ggplot(aes(x = Csection,
                       y = Loading)) +
            geom_boxplot(outlier.shape = NA) +
            geom_point(position = position_jitter(width = 0.25)) +
            theme_bw() +
            xlab("") +
            ylab("Subject loading") + 
            ggtitle("")
          
          return(list(p_feature,
                      p_subject))
        })
      
      p <- 
        cowplot::plot_grid(ps[[1]][[1]], ps[[1]][[2]],
                           nrow = 1,
                           rel_widths = c(1, 0.6),
                           labels = c(paste0("    Axis ", 1,
                                             " (", round(percs[1], 2),
                                             "%)"),
                                      ""))
      
      return(p)
    })

p_supp <- cowplot::plot_grid(plotlist = p_supps,
                             labels = c("A) PCA", "B) CTF"),
                             ncol = 1)
ggsave(p_supp, file = "figures/suppFigure/figure_DIABIMMUNE_supp.pdf",
       width = 7, height = 5)
```

```{r testing}
list(fit_microTensor, fit_pca, fit_ctf) %>% 
  purrr::map(function(fit_decomp) {
    tb_loading <- microTensor::create_loading(fit_decomp = fit_decomp,
                                 feature_names = feature_names,
                                 subject_names = subject_names,
                                 time_names = time_names,
                                 class = "subject")
    tb_loading <- tb_loading %>% 
      dplyr::left_join(df_samples %>% 
                         dplyr::group_by(subjectid) %>% 
                         dplyr::slice(1) %>% 
                         dplyr::ungroup(), 
                       by = c("Subject" = "subjectid")) %>% 
      dplyr::mutate(Csection = ifelse(csection,
                                      "C-section",
                                      "Vaginal"),
                    Loading = `Axis 1`)
    t.test(tb_loading$Loading[tb_loading$csection], tb_loading$Loading[!tb_loading$csection])
  })
```

```{r visualize trajectory}
percs <- fit_microTensor$lambda^2 / sum(fit_microTensor$lambda^2) * 100
ps <- c(1, 2, 3) %>% 
  purrr::map(function(r) {
    # feature
    df_m <- microTensor::create_loading(fit_microTensor,
                                        feature_names = feature_names,
                                        subject_names = subject_names,
                                        time_names = time_names,
                                        class = "feature") %>% 
      dplyr::mutate(
        feature_plot = 
          microTensor::betterGeneraNames(mat_tax[, 3],
                                         mat_tax[, 4],
                                         mat_tax[, 5],
                                         mat_tax[, 6])) %>% 
      dplyr::mutate(m = !!sym(paste0("Axis ", r)))
    
    df_plot <- 
      rbind(
      df_m %>%
        dplyr::arrange(-df_m[["m"]]) %>%
        dplyr::slice(seq_len(5)),
      df_m %>%
        dplyr::arrange(df_m[["m"]]) %>%
        dplyr::slice(seq_len(5)) %>%
        {.[seq(5, 1), ]}
    ) %>%
      dplyr::mutate(feature_plot = factor(feature_plot, 
                                          levels = rev(feature_plot)))
    
    p_feature <- df_plot %>% 
      ggplot(aes(y = m, x = feature_plot)) +
      geom_bar(stat = "identity") +
      coord_flip() +
      theme_bw() +
      theme(axis.title.y = element_blank()) +
      ylab("Feature loading") +
      ggtitle(" ")
    
    # time trajectory
    tb_loading <- microTensor::create_loading(fit_decomp = fit_microTensor,
                                              feature_names = feature_names,
                                              subject_names = subject_names,
                                              time_names = time_names,
                                              class = "sample")
    
    tb_loading <- tb_loading %>% 
      dplyr::mutate(Time = as.integer(as.character(Time))) %>% 
      dplyr::left_join(df_subjects, 
                       by = c("Subject" = "subjectid")) 
    
    tb_loading_avg <- tb_loading %>% 
      dplyr::mutate(`Birth mode` = ifelse(csection, "C-section", "Vaginal")) %>% 
      dplyr::group_by(Time, `Birth mode`) %>% 
      dplyr::summarise(mean_loading = mean(!!sym(paste0("Axis ", r)), na.rm = TRUE),
                       sd_loading = sd(!!sym(paste0("Axis ", r)), na.rm = TRUE) /
                         sqrt(dplyr::n())) %>% 
      dplyr::ungroup() %>% 
      dplyr::mutate(Month = Time - 1)
    
    p_time <- tb_loading_avg %>% 
      dplyr::filter(!is.na(`Birth mode`)) %>% 
      ggplot(aes(x = Month, y = mean_loading,
                 color = `Birth mode`)) +
      geom_line(position = position_dodge(width = 0.5)) +
      geom_point(position = position_dodge(width = 0.5)) +
      geom_errorbar(aes(ymax = mean_loading + sd_loading,
                        ymin = mean_loading - sd_loading),
                    position = position_dodge(width = 0.5),
                    width = 0.5) +
      theme_bw() +
      ylab("Average sample loading") +
      ggtitle("")
    if(r == 1)
      p_time <- p_time + 
      theme(legend.position = c(0, 1),
            legend.justification = c(0, 1),
            legend.background = element_blank())
    else 
      p_time <- p_time + 
      theme(legend.position = "none")
    
    return(list(p_feature,
                p_time))
  })


p_graph <- cowplot::plot_grid(
  ps[[1]][[1]] + ggtitle("Time trajectory"),
  ps[[1]][[2]],
  rel_widths = c(0.8, 1)
)

p_save <- ps[[1]][[2]] + ggtitle("Time trajectory")
ggsave(p_save, filename = "figures/suppFigure/time_DIABIMMUNE.pdf",
       width = 5, height = 4)

p_main <- 
  list(
    cowplot::plot_grid(ps[[1]][[1]], ps[[2]][[1]], ps[[3]][[1]],
                       ncol = 1,
                       align = "v",
                       labels = paste0(c("A", "B", "C"), ") Axis ", c(1, 2, 3),
                                       " (", round(percs[c(1, 2, 3)], 2),
                                       "%)")),
    cowplot::plot_grid(ps[[1]][[2]], ps[[2]][[2]], ps[[3]][[2]],
                       ncol = 1,
                       align = "v")
  ) %>% 
  cowplot::plot_grid(plotlist = .,
                     nrow = 1,
                     align = "h", 
                     rel_widths = c(1, 0.8))
ggsave(p_main, file = "figures/figure6/figure_FARMM.pdf",
       width = 11, height = 6)

feature_check <- dimnames(X_array)[[1]] %>% 
  stringr::str_subset("Bifido") %>% 
  {.[1]}

feature_check2 <- dimnames(X_array)[[1]] %>% 
  stringr::str_subset("Christen") %>% 
  {.[2]}

X_norm <- apply(X_array, c(2, 3), function(x) x / sum(x))

(X_norm[feature_check, , ])%>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("Subject") %>% 
  tidyr::pivot_longer(cols = -Subject, names_to = "month", values_to = "abundance") %>% 
  dplyr::mutate(Month = as.numeric(month) - 1) %>% 
  dplyr::left_join(df_subjects, by = c("Subject" = "subjectid"))  %>% 
  ggplot(aes(x = as.factor(Month), y = log10(abundance + 1e-5), color = csection)) +
  geom_boxplot() +
  geom_line()
```