# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradient_m_cpp <- function(X, Yhat, wt, lambda, vm, vs, vt, normalize = TRUE) {
    .Call(`_microTensor_gradient_m_cpp`, X, Yhat, wt, lambda, vm, vs, vt, normalize)
}

gradient_s_cpp <- function(X, Yhat, wt, lambda, vm, vs, vt, normalize = TRUE) {
    .Call(`_microTensor_gradient_s_cpp`, X, Yhat, wt, lambda, vm, vs, vt, normalize)
}

gradient_t_cpp <- function(X, Yhat, wt, lambda, vm, vs, vt, normalize = TRUE) {
    .Call(`_microTensor_gradient_t_cpp`, X, Yhat, wt, lambda, vm, vs, vt, normalize)
}

gradient_lambda_cpp <- function(X, Yhat, wt, lambda, vm, vs, vt, normalize = TRUE) {
    .Call(`_microTensor_gradient_lambda_cpp`, X, Yhat, wt, lambda, vm, vs, vt, normalize)
}

negLogLik_cpp <- function(X, Yhat, wt, lambda, vm, vs, vt, normalize = TRUE) {
    .Call(`_microTensor_negLogLik_cpp`, X, Yhat, wt, lambda, vm, vs, vt, normalize)
}

rcpp_hello_world <- function(X, y) {
    .Call(`_microTensor_rcpp_hello_world`, X, y)
}

solve_x_vm <- function(L_old, gamma, gradient, X, Yhat, wt, lambda, vm, vs, vt, max_iter = 1000L) {
    .Call(`_microTensor_solve_x_vm`, L_old, gamma, gradient, X, Yhat, wt, lambda, vm, vs, vt, max_iter)
}

test_cpp <- function(X) {
    .Call(`_microTensor_test_cpp`, X)
}

